zeebe:
  client:
    cloud:
      region: bru-2
      clusterId: CLUSTER-ID
      clientId: CLIENT-ID
      clientSecret: CLIENT-SECRET

# Create your API key via https://api-ninjas.com/profile
api-ninjas:
  key: